### ISSUE TITLE
Cannot enable the addon in Blender 2.93.1

### ISSUE THREAD

**Issue by c3f59** [atticus-lv/RenderStackNode#15]
I installed from zip provided [by this repo](https://github.com/atticus-lv/RenderStackNode/releases/tag/v2.0.2), and I get this error message when trying to activate:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'RenderStackNode-2'
```

**Version info:**
![image](https://user-images.githubusercontent.com/45612174/127329120-a058eef1-7b11-43e3-9d84-05e377897f5b.png)

**Comment by c3f59** [comment]
The workaround was to rename the plugin folder in `..\AppData\[...]` to `..\RenderStackNode-2`. Seems an identifier was not updated.

**Comment by atticus-lv** [comment]
it's fix in the develop version
