### ISSUE TITLE
Not completing all the tasks

### ISSUE THREAD

**Issue by ParallelMayhem** [atticus-lv/RenderStackNode#34]
RSN is not completing the task sequence in some cases.

Here is my node setup:
![image](https://user-images.githubusercontent.com/40900509/175431251-da2910ae-b94a-45fb-8a9f-10e828bb341e.png)

It renders out the first frame/task and then stops.

**Comment by atticus-lv** [comment]
Can you update a fille(with clean scene) for me to check?

**Comment by atticus-lv** [comment]
Hi , do you still have this issue?

**Comment by atticus-lv** [comment]
Close it for no reply for a long time, but you can open this issue at any time you want.
